import test from 'node:test';
import assert from 'node:assert/strict';
import {byName} from '../lib/game.ts';
import {addAccountReward,buyResearch,clearAccountReward,completionReward,emptyAccountProgress,researchAttackPercent,researchAvailable,researchBossCitizens,researchBossGold,researchBossTroops,researchDeployLimit,researchGambleDiscountPercent,researchNodes,researchQuestCitizens,researchQuestGold,researchQuestTroops,researchSpeedPercent,researchStartCitizens,researchStartGold,researchStartTroops,xpForNextLevel} from '../lib/research.ts';
import {readPlayer} from '../lib/player.ts';

test('legacy profiles receive account progression defaults',()=>{const player=readPlayer(JSON.stringify({version:1,nickname:'테스터',prologueComplete:true}));assert.equal(player.level,1);assert.equal(player.xp,0);assert.equal(player.accountGold,0);assert.deepEqual(player.research,{});});
test('research respects account level, prerequisite and account gold',()=>{let account={...emptyAccountProgress(),accountGold:5000};const speed=researchNodes.find(node=>node.id==='speed-1');assert.equal(researchAvailable(speed,account),false);account=buyResearch(account,'attack-1');assert.equal(account.accountGold,4500);assert.equal(buyResearch(account,'speed-1'),null);account.level=2;account=buyResearch(account,'speed-1');assert.equal(account.research['speed-1'],1);});
test('support research changes starting resources and clear bonuses',()=>{const research={'start-gold':1,'start-troop':1,'start-citizen':1,'clear-xp':1,'clear-gold':1};assert.equal(researchStartGold(research),100);assert.equal(researchStartTroops(research),1);assert.equal(researchStartCitizens(research),1);assert.deepEqual(clearAccountReward(1,1,'normal',research),{gold:263,xp:131});});
test('repeat clears award half the account gold and experience',()=>{const reward={gold:301,xp:155};assert.deepEqual(completionReward(reward,true),reward);assert.deepEqual(completionReward(reward,false),{gold:151,xp:78});});
test('account rewards level up and research damage targets the intended units',()=>{const leveled=addAccountReward(emptyAccountProgress(),{gold:250,xp:100});assert.equal(leveled.level,2);assert.equal(leveled.xp,0);assert.equal(leveled.accountGold,250);assert.equal(xpForNextLevel(2),175);const research={'attack-1':1,'mastery-1':1,'role-전열':1,'hero-온달':1};assert.equal(researchAttackPercent(byName.창병,research),4);assert.equal(researchAttackPercent(byName.온달,research),5);});
test('hero research grants two percent attack and speed at three-level intervals',()=>{const seohee=researchNodes.find(node=>node.id==='hero-서희'),ondal=researchNodes.find(node=>node.id==='hero-온달'),sungkyum=researchNodes.find(node=>node.id==='hero-신숭겸');assert.equal(seohee.unlockLevel,13);assert.equal(ondal.unlockLevel,13);assert.equal(sungkyum.unlockLevel,16);const research={'hero-서희':1,'speed-1':1};assert.equal(researchAttackPercent(byName.서희,research),2);assert.equal(researchSpeedPercent(research,byName.서희),3);assert.equal(researchSpeedPercent(research,byName.온달),1);});
test('support research spans level seventy and exposes gameplay bonuses',()=>{const support=researchNodes.filter(node=>node.tab==='support');assert.equal(support[0].unlockLevel,1);assert.equal(support.at(-1).unlockLevel,70);assert.ok(support.every(node=>Number.isInteger(node.iconIndex)));const research=Object.fromEntries(['deploy-1','support-mastery-6','quest-gold','quest-troop','quest-citizen','gamble-refund','gamble-pity','boss-gold','boss-troop-1','boss-troop-2','boss-citizen-1'].map(id=>[id,1]));assert.equal(researchDeployLimit(research),2);assert.equal(researchQuestGold(research),100);assert.equal(researchQuestTroops(research),1);assert.equal(researchQuestCitizens(research),1);assert.equal(researchGambleDiscountPercent(research),10);assert.equal(researchBossGold(research),100);assert.equal(researchBossTroops(research),3);assert.equal(researchBossCitizens(research),1);});
